version: 1.0
disable_existing_loggers: False
formatters:
  brief:
    format: "%(asctime)s-%(message)s"
    datefmt: "%Y %a %d %H:%M:%S"
  simple:
    format: "%(asctime)s-%(name)s-%(levelname)s-%(message)s"
    datefmt: "%Y %a %d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: INFO
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: simple
    when: midnight
    level: INFO
    filename: "/log/proxypool/proxypool.log"
  getterfile:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: simple
    when: midnight
    level: INFO
    filename: "/log/proxypool/proxypool-getter.log"
  testerfile:
    class: logging.handlers.TimedRotatingFileHandler
    # mode: 'a'
    formatter: simple
    when: midnight
    # maxBytes: 10485760 # 10MB
    # backupCount: 20
    level: INFO
    filename: "/log/proxypool/proxypool-tester.log"
loggers:
  proxypool-getter:
    level: INFO
    handlers: [console, getterfile]
  proxypool-tester:
    level: INFO
    handlers: [console, testerfile]
  proxypool:
    level: INFO
    handlers: [console, file]
# root:
#   level: INFO
#   handlers: [console]
