version: 1.0
disable_existing_loggers: False
formatters:
  brief:
    format: "%(asctime)s-%(message)s"
    datefmt: "%Y %a %d %H:%M:%S"
  simple:
    format: "%(asctime)s-%(name)s-%(levelname)s-%(message)s"
    datefmt: "%Y %a %d %H:%M:%S"
handlers:
  console:
    class : logging.StreamHandler
    formatter: brief
    level   : INFO
  file:
    class : logging.FileHandler
    mode: 'w'
    formatter: simple
    level: INFO
    filename: '/log/proxypool/proxypool.log'
  errorfile:
    class : logging.handlers.TimedRotatingFileHandler
    # mode: 'a'
    formatter: simple
    when: midnight
    # maxBytes: 10485760 # 10MB
    # backupCount: 20
    level: ERROR
    filename: '/log/proxypool/proxypool_error.log'
loggers:
  proxypool:
    level: INFO
    handlers: [console, file, errorfile]
# root:
#   level: INFO
#   handlers: [console]